# Generated by Django 5.0.2 on 2024-02-28 10:46

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1024, verbose_name='Tytuł char')),
                ('content', models.TextField(verbose_name='Zawartość text')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=pages.models.get_image_filepath)),
                ('added', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
