# Generated by Django 5.0.3 on 2024-03-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='image',
            new_name='images',
        ),
    ]
