# Generated by Django 5.0.3 on 2024-03-14 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_coment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coment',
            options={'ordering': ['-added']},
        ),
    ]
