# Generated by Django 5.0.3 on 2024-03-24 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_post_dislikes_post_likes_reaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
    ]
